name: Daily Auto Commit

on:
  schedule:
    - cron: '0 5 * * *'  # Har kuni soat 5:00 UTC (Toshkent vaqti bilan 10:00)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set timezone
        run: sudo timedatectl set-timezone Asia/Tashkent

      - name: Make random commit count
        id: random_commit
        run: |
          RANDOM_NUMBER=$((RANDOM % 5 + 1))  # 1 dan 5 gacha random son
          echo "Random commit count: $RANDOM_NUMBER"
          echo "commit_count=$RANDOM_NUMBER" >> $GITHUB_ENV

      - name: Make changes and commit
        run: |
          for i in $(seq 1 $commit_count); do
            echo "$(date) - auto update $i" >> log.txt
            git config --global user.name "SardorBot"
            git config --global user.email "sardor@example.com"
            git add .
            git commit -m "Daily auto commit $i"
          done

      - name: Push changes
        run: git push
        